"""
Optional: email the analysis (PDF report) to yourself or a family member.

This needs YOUR OWN SMTP credentials to actually send anything -- there's
no shared Anthropic/WattWise mail server. The simplest free option is a
Gmail "App Password" (not your normal Gmail password):
  1. Enable 2-Step Verification on the Google account
  2. Go to https://myaccount.google.com/apppasswords
  3. Generate an app password for "Mail"
  4. Set these in your .env file:
       SMTP_HOST=smtp.gmail.com
       SMTP_PORT=587
       SMTP_USER=youraddress@gmail.com
       SMTP_PASS=the-16-character-app-password

Without these set, send_report_email() returns a clear "not configured"
result instead of crashing, same pattern as llm.py's GEMINI_API_KEY check.
"""

import os
import smtplib
from email.message import EmailMessage

SMTP_HOST = os.environ.get("SMTP_HOST")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER")
SMTP_PASS = os.environ.get("SMTP_PASS")


def is_configured() -> bool:
    return all([SMTP_HOST, SMTP_USER, SMTP_PASS])


def send_report_email(to_email: str, pdf_path: str, subject: str = "Your WattWise Energy Report") -> dict:
    if not is_configured():
        return {"success": False,
                "message": "Email isn't configured yet. Set SMTP_HOST, SMTP_USER, and SMTP_PASS "
                           "in your .env file (see the comment at the top of email_service.py)."}

    if not os.path.exists(pdf_path):
        return {"success": False, "message": "Report PDF not found -- try analyzing the bill again."}

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = SMTP_USER
    msg["To"] = to_email
    msg.set_content(
        "Hi,\n\nAttached is your WattWise electricity bill analysis, "
        "generated by Wattson.\n\n-- WattWise"
    )

    with open(pdf_path, "rb") as f:
        msg.add_attachment(f.read(), maintype="application", subtype="pdf",
                            filename=os.path.basename(pdf_path))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=15) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.send_message(msg)
        return {"success": True, "message": f"Report sent to {to_email}."}
    except smtplib.SMTPException as e:
        return {"success": False, "message": f"Email failed to send: {e}"}
    except OSError as e:
        return {"success": False, "message": f"Couldn't reach the mail server: {e}"}
