"""
PDF export -- turns one analyzed bill (or a history record) into a clean
downloadable PDF report using fpdf2 (lightweight, no system dependencies
like wkhtmltopdf or a browser engine).
"""

import os
from fpdf import FPDF

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "exports")
os.makedirs(OUTPUT_DIR, exist_ok=True)


class WattWiseReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(20, 30, 60)
        self.cell(0, 12, "WattWise -- Electricity Bill Analysis", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, 22, 200, 22)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by WattWise -- WattWise Energy Score is a heuristic, not an official utility rating.", align="C")


def _section_title(pdf: FPDF, text: str):
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(255, 180, 0)
    pdf.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(30, 30, 30)


def _clean(text) -> str:
    """fpdf2's core fonts (Helvetica) are latin-1 only -- strip/replace
    characters like ₹ and smart quotes that would otherwise crash generation."""
    if text is None:
        return "-"
    text = str(text)
    replacements = {"₹": "Rs. ", "\u2019": "'", "\u2018": "'", "\u201c": '"',
                     "\u201d": '"', "\u2013": "-", "\u2014": "-", "\u2026": "..."}
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text.encode("latin-1", "replace").decode("latin-1")


def generate_bill_pdf(bill_data: dict, metrics: dict, score: dict,
                       ai_analysis: str, breakdown: dict | None = None,
                       filename: str = "wattwise_report.pdf") -> str:
    """Build the PDF and return the full path it was saved to."""
    pdf = WattWiseReport()
    pdf.add_page()

    _section_title(pdf, "Bill Summary")
    pdf.set_font("Helvetica", "", 11)
    rows = [
        ("Consumer Number", bill_data.get("consumer_number")),
        ("Billing Month", bill_data.get("billing_month")),
        ("Units Consumed", bill_data.get("units_consumed")),
        ("Bill Amount", f"Rs. {bill_data.get('bill_amount')}" if bill_data.get("bill_amount") else None),
        ("Change vs Previous", f"{metrics.get('percentage_change')}% ({metrics.get('trend')})"),
        ("Cost per Unit", f"Rs. {metrics.get('cost_per_unit')}" if isinstance(metrics.get("cost_per_unit"), (int, float)) else "-"),
        ("WattWise Energy Score", f"{score.get('score')}/100 -- {score.get('rating')}"),
    ]
    for label, value in rows:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(60, 8, _clean(label), border=0)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, _clean(value), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    if breakdown:
        _section_title(pdf, "Appliance Contribution")
        pdf.set_font("Helvetica", "", 11)
        for name, data in breakdown.items():
            pdf.cell(0, 7, _clean(f"{name}: {data['kwh']} kWh/month ({data['percent_share']}%)"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    _section_title(pdf, "Wattson's Analysis")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 7, _clean(ai_analysis))
    pdf.ln(4)

    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(130, 130, 130)
    pdf.multi_cell(0, 6, _clean(
        "Note: The WattWise Energy Score is our own heuristic based on consumption "
        "trend and usage band -- it is not an official MSEDCL or government rating. "
        "Appliance estimates use rated wattage and typical duty-cycle factors, not a "
        "live meter reading."
    ))

    path = os.path.join(OUTPUT_DIR, filename)
    pdf.output(path)
    return path


if __name__ == "__main__":
    sample_bill = {"consumer_number": "123456789012", "billing_month": "June 2026",
                    "units_consumed": 420, "bill_amount": 3650.0}
    sample_metrics = {"percentage_change": 44.83, "trend": "increased", "cost_per_unit": 8.69}
    sample_score = {"score": 45, "rating": "High Consumption"}
    sample_breakdown = {"AC": {"kwh": 234.0, "percent_share": 79.8}}
    path = generate_bill_pdf(sample_bill, sample_metrics, sample_score,
                              "Your consumption increased by about 45%, likely due to AC usage.",
                              sample_breakdown, filename="test_report.pdf")
    print("Saved to:", path)
